package me.chosante.common

import kotlinx.serialization.Serializable

@Serializable
enum class Rarity {
    COMMON,
    UNCOMMON,
    RARE,
    MYTHIC,
    LEGENDARY,
    RELIC,
    SOUVENIR,
    EPIC,
    ;
}

@Serializable
enum class ItemType {
    AMULET,
    EMBLEM,
    SHOULDER_PADS,
    RING,
    BOOTS,
    ONE_HANDED_WEAPONS,
    CHEST_PLATE,
    CAPE,
    OFF_HAND_WEAPONS,
    HELMET,
    PETS,
    TWO_HANDED_WEAPONS,
    MOUNTS,
    BELT,
    ;
}

@Serializable
data class Equipment(
    val equipmentId: Int,
    val level: Int,
    val name: String,
    val rarity: Rarity,
    val itemType: ItemType,
    val characteristics: Map<Characteristic, Int>,
)

@Serializable
enum class Characteristic {
    MASTERY_ELEMENTARY,
    MASTERY_ELEMENTARY_ONE_RANDOM_ELEMENT,
    MASTERY_ELEMENTARY_TWO_RANDOM_ELEMENT,
    MASTERY_ELEMENTARY_THREE_RANDOM_ELEMENT,
    MASTERY_ELEMENTARY_WATER,
    MASTERY_ELEMENTARY_WIND,
    MASTERY_ELEMENTARY_FIRE,
    MASTERY_ELEMENTARY_EARTH,
    MASTERY_DISTANCE,
    MASTERY_CRITICAL,
    MASTERY_BACK,
    MASTERY_MELEE,
    MASTERY_BERSERK,
    MASTERY_HEALING,
    RESISTANCE_CRITICAL,
    RESISTANCE_BACK,
    RESISTANCE_ELEMENTARY,
    RESISTANCE_ELEMENTARY_ONE_RANDOM_ELEMENT,
    RESISTANCE_ELEMENTARY_TWO_RANDOM_ELEMENT,
    RESISTANCE_ELEMENTARY_THREE_RANDOM_ELEMENT,
    RESISTANCE_ELEMENTARY_EARTH,
    RESISTANCE_ELEMENTARY_FIRE,
    RESISTANCE_ELEMENTARY_WATER,
    RESISTANCE_ELEMENTARY_WIND,
    HP,
    CRITICAL_HIT,
    WAKFU_POINT,
    MAX_WAKFU_POINTS,
    ACTION_POINT,
    MAX_ACTION_POINT,
    RANGE,
    MOVEMENT_POINT,
    MAX_MOVEMENT_POINT,
    CONTROL,
    WISDOM,
    DODGE,
    LOCK,
    PROSPECTION,
    INITIATIVE,
    WILLPOWER,
    BLOCK_PERCENTAGE,
    GIVEN_ARMOR_PERCENTAGE,
    RECEIVED_ARMOR_PERCENTAGE,
    HERBALIST_HARVEST_QUANTITY_PERCENTAGE,
    LUMBERJACK_HARVEST_QUANTITY_PERCENTAGE,
    TRAPPER_HARVEST_QUANTITY_PERCENTAGE,
    MINER_HARVEST_QUANTITY_PERCENTAGE,
    FARMER_HARVEST_QUANTITY_PERCENTAGE,
    FISHERMAN_HARVEST_QUANTITY_PERCENTAGE,
    ;
}
