type=fix
en=Badges no longer claim a build is closer to the best than it is when items with negative critical hit are involved
fr=Les badges ne présentent plus un build comme plus proche du meilleur qu'il ne l'est quand des objets à Coup Critique négatif entrent en jeu
