type=feat
en=Most Masteries searches with a Range target or targets set to 0 now get a "proven within X%" badge
fr=Les recherches Max maîtrises avec une cible de Portée ou des cibles à 0 ont désormais un badge « Optimal prouvé à X% près »
