type=fix
en=Max-damage and most-masteries searches with high-level items are faster again since the item stat conditions
fr=Tes recherches dégâts max et maîtrises max avec des objets de haut niveau sont de nouveau plus rapides depuis les conditions de caractéristiques des objets
