name: Deploy
on: [workflow_dispatch]
jobs:
    build:
        # Use the Build workflow described above
        uses: ./.github/workflows/build.yml
    deploy:
        needs: [build]
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Gradle
              uses: gradle/gradle-build-action@v3.5.0

            - name: Create Jars
              run: ./gradlew jar

            - name: Run Conveyor
              uses: hydraulic-software/conveyor/actions/build@v14.3
              env:
                OAUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  extra_flags: '-f ./gui/conveyor.conf'
                  command: make copied-site
                  signing_key: ${{ secrets.SIGNING_KEY }}
                  agree_to_license: 1
